apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
- frontend.yaml
- catalog.yaml
- orders.yaml
- ingress.yaml
- catalog_queue_serviceclaim.yaml
- catalog_rds_psql_serviceclaim.yaml
- orders_table_serviceclaim.yaml
