apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
- frontend.yaml
- catalog.yaml
- orders.yaml
- ingress.yaml
- catalog_queue_serviceclaim.yaml
- catalog_rds_psql_serviceclaim.yaml
- orders_table_serviceclaim.yaml
images:
- name: demo-app/catalog
  newName: ghcr.io/primaza/demo-app/catalog
- name: demo-app/catalog-init
  newName: ghcr.io/primaza/demo-app/catalog-init
- name: demo-app/frontend
  newName: ghcr.io/primaza/demo-app/frontend
- name: demo-app/orders
  newName: ghcr.io/primaza/demo-app/orders
- name: demo-app/orders-init
  newName: ghcr.io/primaza/demo-app/orders-init
